### ISSUE TITLE
segment URI format changed?

### ISSUE THREAD

**Issue by X1011** [ilyalissoboi/twitch_downloader#1] opened 2016-04-16 10:45 UTC
So I was trying to download part of a VoD, and this error happened:

```
$ downloader.py -u http://twitch.tv/alientonx/v/51266818 -s 7640
Traceback (most recent call last):
  File "/home/dan/bin/vendor/downloader.py", line 173, in <module>
    filename, start_byte, end_byte = p.groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

So I think `_chunk_re` isn't matching `seg.absolute_uri`, so I put in a print statement, and the URI it had is `http://vod.ak.hls.ttvnw.net/s3_vods/44d3b12fce_alientonx_19873633120_408993748/high/index-0000003839-OUtB-muted-3607532.ts`, which doesn't have the expected `\?start_offset=(\d+)&end_offset=(\d+)`.

**Comment by ilyalissoboi** [comment] 2016-04-17 02:53
It does seem like Twitch is generating a different type of M3U8 playlist for that particular VOD. Please let me know if you find any more channels/videos that produce the same error, since I couldn't really reproduce this behavior on any of the channels I normally watch or even any of the other videos on the same channel that you mentioned. 

Going to consider it a Twitch API bug for now, but it should be possible to add support for these, if more VODs like this pop up.

**Comment by X1011** [comment] 2016-04-19 09:27
same thing happened with all 5 other VoDs I tried:

```
$ downloader.py -u http://twitch.tv/alientonx/v/49297207 -s 16092
http://vod.ak.hls.ttvnw.net/9763cfdcad_alientonx_19766866368_406094376/high/index-0000008069-CfjP-1995056.ts
$ downloader.py -u http://twitch.tv/alientonx/v/51463466 -s 16688
http://vod.ak.hls.ttvnw.net/4268f24fb1_alientonx_19895217008_409574983/high/index-0000008369-0pnx-9605860.ts
$ downloader.py -u http://twitch.tv/alientonx/v/51643296 -s 14092
http://vod.edgecast.hls.ttvnw.net/1413185ee8_alientonx_19913348624_410052103/high/index-0000007079-sPVW-399312.ts
$ downloader.py -u http://www.twitch.tv/scrubing/v/48852718
http://vod.ak.hls.ttvnw.net/cde9b581b4_scrubing_19744821952_405515579/high/index-0000000029-5gsX-muted-0.ts
$ downloader.py -u http://www.twitch.tv/dizzykitten/v/48903237
http://vod.ak.hls.ttvnw.net/c83a760768_dizzykitten_19748321840_405609292/high/index-0000000029-Bjon-muted-0.ts
```

**Comment by ilyalissoboi** [comment] 2016-05-27 07:03
I finally got time to look into this now and it seems that all the VODs you encountered this bug on were flagged for deletion. Or, at least, that is my theory, since none of those seem to be available on Twitch anymore. I'd like to fix the script behavior to handle these properly (for as long as they remain on the server, anyway), but I'll need some new videos for that, so please let me know if you find any more VODs like this.

**Comment by X1011** [comment] 2016-05-30 04:08
Ok, after some testing, there does seem to be a time cutoff, but it doesn't line up with the 14 days [Twitch says](http://help.twitch.tv/customer/portal/articles/1575302-videos-on-demand) it saves broadcasts for, nor the ~2 months I've observed the VoDs actually being available before disappearing.

On the 2 channels i tested, i'm seeing VoDs dated April 9 or later having the start and end offset parameters, and VoDs dated April 8 or earlier not:

```
#April 8:
* $ dltest https://www.twitch.tv/alientonx/v/59248849
http://vod.ak.hls.ttvnw.net/56f73c99e0_alientonx_20690940624_432364047/high/index-0000000029-0wv5-0.ts
#April 9:
* $ dltest https://www.twitch.tv/alientonx/v/59444826
http://vod.ak.hls.ttvnw.net/v1/AUTH_system/vods_be31/alientonx_20709695152_432978876/high/index-0000000029-Zr2y.ts?start_offset=0&end_offset=200595

#April 8:
* $ dltest https://www.twitch.tv/dizzykitten/v/59245131
http://vod.cf.hls.ttvnw.net/e63efd539d_dizzykitten_20690629872_432353910/high/index-0000000029-N9Fm-muted-0.ts
#April 9:
* $ dltest https://www.twitch.tv/dizzykitten/v/59439517
http://vod.ak.hls.ttvnw.net/v1/AUTH_system/vods_aeec/dizzykitten_20709251968_432964259/high/index-0000000029-Vl4g.ts?start_offset=0&end_offset=237067
```

**Comment by ilyalissoboi** [comment] 2016-06-01 06:03
I have pushed a temporary fix for this to master. I added an alternative regular expression for URLs without byte offsets (since we don't really need them per se). You should be able to download the previously broken videos now.

I am going to do a bit of refactoring to have everything download via a common code path later this week.

**Closed as completed** 2016-06-01 06:49 UTC
Labels: bug
